#balenalib/<hw>-<distro>-<lang_stack>:<lang_ver>-<distro_ver>-(build|run)-<yyyymmdd>
# parent image with updated packages
FROM balenalib/amd64-debian:buster-run as nextdom-base

MAINTAINER info@nextdom.com

ARG PHPVERdef
ENV PHPVER=${PHPVERdef:-php7.4}
ARG aptcacher

RUN echo "base param branch: ${BRANCH} / version: ${VERSION} / tarBall: ${TAR} / initSh: ${initSh} / phpVer: ${PHPVER} / apt-cache: ${aptcacher} / git url: ${URLGIT} "
RUN if [ ! -z ${aptcacher} ]; then echo "Acquire::http::Proxy \"http://${aptcacher}:3142\";" >/etc/apt/apt.conf.d/01proxy && \
    echo "Acquire::https::Proxy \"http://${aptcacher}:3142\";" >>/etc/apt/apt.conf.d/01proxy && cat /etc/apt/apt.conf.d/01proxy ; fi;\
    apt-get update && apt-get install -y apt-transport-https apt-utils iputils-ping && \
    apt-get install -y lsb-release wget git apache2 php${PHPVER} php${PHPVER}-curl php${PHPVER}-mbstring apache2 apache2-utils libexpat1 \
    php${PHPVER} php${PHPVER}-curl php${PHPVER}-gd php${PHPVER}-imap php${PHPVER}-json php${PHPVER}-mysql \
    php${PHPVER}-xml php${PHPVER}-opcache php${PHPVER}-soap php${PHPVER}-xmlrpc libapache2-mod-php${PHPVER} php${PHPVER}-common \
    php${PHPVER}-dev php${PHPVER}-zip php${PHPVER}-ssh2 php${PHPVER}-mbstring php${PHPVER}-ldap iputils-ping \
    php-xml php-zip unzip python-jsmin \
    wget supervisor mariadb-client ntp ca-certificates unzip curl sudo cron tar wget ntpdate htop iotop iftop smbclient python python-pip \
    software-properties-common libexpat1 ssl-cert && \
    wget https://deb.nodesource.com/setup_10.x -O /tmp/nodeTmp && \
    cat /etc/apt/apt.conf.d/01proxy && \
    /bin/bash -x ./tmp/nodeTmp && \
    rm /etc/apt/apt.conf.d/01proxy && \
    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; php composer-setup.php --install-dir=. --filename=composer --quiet; mv composer /usr/local/bin/; chmod +x /usr/local/bin/composer
#CMD [ "/bin/bash", "-c", "--" , "trap : TERM INT; sleep infinity & wait" ]