#balenalib/<hw>-<distro>-<lang_stack>:<lang_ver>-<distro_ver>-(build|run)-<yyyymmdd>
#FROM debian:latest as builder
FROM balenalib/amd64-debian:buster-run as base

MAINTAINER info@nextdom.com

ARG initShdef
ENV initSh=${initShdef:-init.sh}
ARG POSTINST_DEBUG
ARG BRANCHdef
ENV BRANCH=${BRANCHdef:-master}
ARG VERSIONdef
ENV VERSION=${VERSIONdef:-}
ARG PHPVERdef
ENV PHPVER=${PHPVERdef:-php7.4}
ARG URLGITdef
ENV URLGIT=${URLGITdef:-noGitUrl}
ARG TARdef
ENV TAR=${TARdef:-none}
ARG aptcacher

RUN echo "base param branch: ${BRANCH} / version: ${VERSION} / tarBall: ${TAR} / initSh: ${initSh} / phpVer: ${PHPVER} / apt-cache: ${aptcacher} / git url: ${URLGIT} "
RUN apt-get update
#RUN apt-cache search ^php | grep ^php
RUN echo "Acquire::http::Proxy \"http://${aptcacher}:3142\";" >/etc/apt/apt.conf.d/01proxy && \
    echo "Acquire::https::Proxy \"http://${aptcacher}:3142\";" >>/etc/apt/apt.conf.d/01proxy && cat /etc/apt/apt.conf.d/01proxy
RUN apt-get install -y apt-transport-https apt-utils && \
 apt-get install -y lsb-release wget git apache2 php${PHPVER} php${PHPVER}-curl php${PHPVER}-mbstring php-xml php-zip unzip python-jsmin && \
 wget https://deb.nodesource.com/setup_10.x -O /tmp/nodeTmp && \
 cat /etc/apt/apt.conf.d/01proxy && \
 unset http_proxy && unset https_proxy && \
 /bin/bash -x ./tmp/nodeTmp && \
 rm /etc/apt/apt.conf.d/01proxy
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"; php composer-setup.php --install-dir=. --filename=composer --quiet; mv composer /usr/local/bin/; chmod +x /usr/local/bin/composer
