version: '3.6'
services:
  web:
    image: edgd1er/nextdom-web-deb:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD","curl","-f","http://localhost/public/here.html"]
      interval: 10s
      timeout: 10s
    expose:
      - "80"
      - "443"
    ports:
      - "9180:80"
      - "9543:443"
    environment:
      - TZ=Europe/Paris
      - MYSQL_ROOT=changeIt
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=3306
      - MYSQL_NEXTDOM_DB=nextdomTest
      - MYSQL_NEXTDOM_USER=nextdom_user
      - MYSQL_NEXTDOM_PASSWD=changeIt
    #    stdin_open: true
    #    tty: true
    depends_on:
      - mysql

  mysql:
    #image: mysql/mysql-server:5.7
    image: mariadb
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=changeIt
      - MYSQL_DATABASE=nextdomTest
      - MYSQL_USER=nextdom_user
      - MYSQL_PASSWORD=changeIt
    restart: unless-stopped
    expose:
      - "3306"
    ports:
      - "3326:3306"
    #volumes:
    #  - mysqldata-prod:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9281:8080"